Resource:
  QuiztopiaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.QUIZ_TABLE}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
