Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.USERS_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        # - AttributeName: username
        #   KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  QuizzesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.QUIZ_TABLE}
      AttributeDefinitions:
        - AttributeName: quizId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: quizId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  LeaderboardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.LEADERBOARD_TABLE}
      AttributeDefinitions:
        - AttributeName: quizId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: score
          AttributeType: N
      KeySchema:
        - AttributeName: quizId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ScoreIndex
          KeySchema:
            - AttributeName: quizId
              KeyType: HASH
            - AttributeName: score
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
